# Generated by Django 3.0.4 on 2020-04-06 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(max_length=255)),
                ('price', models.PositiveIntegerField(verbose_name='Product Price')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock of Products')),
                ('type', models.CharField(max_length=20, verbose_name='Product Type')),
                ('offer', models.CharField(max_length=50)),
                ('delevery_charge', models.CharField(max_length=20)),
                ('default_photo', models.ImageField(help_text='Product default image.', upload_to='product_image')),
                ('free_delivery', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.Product')),
            ],
            options={
                'verbose_name': 'Product Photo',
                'verbose_name_plural': 'Product Photos',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.Product')),
            ],
        ),
    ]
