# Generated by Django 3.0.4 on 2020-04-25 18:32

import apps.product.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.PositiveIntegerField(default=apps.product.models.OrderPayment.number, unique=True)),
                ('product_list', jsonfield.fields.JSONField()),
                ('delivery_location', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=11)),
                ('payment_number', models.CharField(blank=True, max_length=11, null=True)),
                ('delivery_charge', models.CharField(default='Depends on courier.', max_length=50)),
                ('total', models.CharField(max_length=255)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('city', models.CharField(max_length=20)),
                ('payment_gateway', models.CharField(default='Cash on delivery.', editable=False, max_length=50)),
                ('is_delivered', models.BooleanField(default=False, help_text='Is products are delivered?')),
            ],
            options={
                'verbose_name': 'Order and Payment',
                'verbose_name_plural': 'Order and Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.PositiveSmallIntegerField(blank=True, help_text='Phone Number.', null=True)),
                ('payment_gateway', models.CharField(choices=[('Bkash', 'Bkash'), ('Rocket', 'Rocket'), ('Nagad', 'Nagad')], default=('Bkash', 'Bkash'), max_length=20)),
                ('image', models.ImageField(upload_to='service_image')),
            ],
            options={
                'verbose_name': 'Payment Phone Number',
                'verbose_name_plural': 'Payment Phone Numbers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(max_length=255)),
                ('price', models.PositiveIntegerField(verbose_name='Product Price')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock of Products')),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Constructions', 'Constructions'), ('Home Decorations', 'Home Decorations'), ('Electronics', 'Electronics'), ('Others', 'Others'), ('Kids World', 'Kids World')], default=('Men', 'Men'), max_length=20, verbose_name='Product Category')),
                ('sub_category', models.CharField(choices=[('Watch', 'Watch'), ('Belt', 'Belt'), ('Wallet', 'Wallet'), ('Shoe', 'Shoe'), ('Sunglass', 'Sunglass'), ('Ornaments', 'Ornaments'), ('Phrase', 'Phrase'), ('Safety Equipments', 'Safety Equipments'), ('Tools', 'Tools'), ('Machinery', 'Machinery'), ('Hardware', 'Hardware'), ('Sanitary', 'Sanitary'), ('Washing Device', 'Washing Device'), ('Water Purifiers', 'Water Purifiers'), ('Kitchen & Cleaning', 'Kitchen & Cleaning'), ('CC Camera', 'CC Camera'), ('Earphone', 'Earphone'), ('Scale', 'Scale'), ('Storage Device', 'Storage Device'), ('Network Device', 'Network Device'), ('Health Caret', 'Health Care'), ('Stationery', 'Stationery'), ('Rain Coat', 'Rain Coat'), ('Kids Toys', 'Kids Toys'), ('Bag', 'Bag')], default=('Watch', 'Watch'), max_length=20, verbose_name='Product Sub-Category')),
                ('offer', models.CharField(blank=True, max_length=50, null=True)),
                ('default_photo', models.ImageField(help_text='size must be ato ato pixel.', upload_to='default_photo')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('trend_name', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Can add only 3 images please.', upload_to='product_images')),
            ],
            options={
                'verbose_name': 'Product Photo',
                'verbose_name_plural': 'Product Photos',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reward_images')),
                ('reward_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reward Title')),
                ('position', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('sub_title', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='slider_image')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(max_length=250)),
                ('twitter', models.URLField(max_length=250)),
                ('youtube', models.URLField(max_length=250)),
                ('instagram', models.URLField(max_length=250)),
                ('contact_mail', models.EmailField(max_length=120)),
                ('information_mail', models.EmailField(max_length=250)),
                ('customer_care', models.URLField(max_length=250)),
                ('complain_suggestion', models.URLField(max_length=250)),
                ('order_confirmation', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='trend_images')),
                ('position', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Trend',
                'verbose_name_plural': 'Trends',
            },
        ),
        migrations.CreateModel(
            name='UpdateNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Updated News',
                'verbose_name_plural': 'Updated News',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.Product')),
            ],
        ),
    ]
