# Generated by Django 3.0.4 on 2020-04-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200426_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentphonenumber',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number.', max_length=11, null=True),
        ),
    ]
