# Generated by Django 3.0.4 on 2020-04-08 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
