# Generated by Django 3.0.4 on 2020-04-08 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('sub_title', models.CharField(max_length=40)),
                ('photo', models.ImageField(upload_to='slider_image')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='UpdateNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'men'), ('Women', 'women')], default=django.utils.timezone.now, max_length=20, verbose_name='Product Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Belt', 'belt'), ('Watch', 'watch')], default=2, max_length=20, verbose_name='Product Sub-Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='default_photo',
            field=models.ImageField(help_text='size must be ato ato pixel.', upload_to='default_photo'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(upload_to='product_images'),
        ),
    ]
