# Generated by Django 3.0.4 on 2020-04-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200427_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_photo',
            field=models.ImageField(help_text='<h2 style="color: #008CBA;">Images size must be height: 1200px and width: 1486px format.</h2>', upload_to='default_photo'),
        ),
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(help_text='<h2 style="color: #008CBA;">Images size must be height: 1200px and width: 1486px format.</h2><br>Can add only 3 images please.', upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(help_text='<h2 style="color: #008CBA;">Images size must be height: 1920px and width: 930px format.</h2>', upload_to='slider_image'),
        ),
        migrations.AlterField(
            model_name='trend',
            name='image',
            field=models.ImageField(help_text='<h2 style="color: #008CBA;">Images size must be height: 1200px and width: 809px format.</h2>', upload_to='trend_images'),
        ),
    ]
