# Generated by Django 3.0.4 on 2020-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200408_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'men'), ('Women', 'women')], default=('Men', 'men'), max_length=20, verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Belt', 'belt'), ('Watch', 'watch')], default=('Belt', 'belt'), max_length=20, verbose_name='Product Sub-Category'),
        ),
    ]
