# Generated by Django 3.0.4 on 2020-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200408_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'men'), ('Women', 'women'), ('Construction', 'construction'), ('Home_Decorations', 'home_decorations'), ('Electronic', 'electronic'), ('Others', 'others'), ('Kids_World', 'kids_world')], default=('Men', 'men'), max_length=20, verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Watch', 'watch'), ('Belt', 'betl'), ('Wallet', 'wallet'), ('Shoe', 'shoe'), ('Sunglass', 'sunglass'), ('Ornaments', 'ornaments'), ('Phrase', 'phrase'), ('Safety_Equipment’s ', 'safey_equipments'), ('Tools', 'tools'), ('Machinery', 'machinery'), ('Hardware', 'hardware'), ('Sanitary', 'sanitary'), ('Washing_Device', 'washing_device'), ('Water_Purifiers', 'water_purifiers'), ('Kitchen_&_Cleaning', 'kitchen_&_cleaning'), ('CC_Camera', 'cc_camera'), ('Earphone', 'earphone'), ('Scale', 'scale'), ('Storage_Device', 'storage_device'), ('Network_Device', 'network_device'), ('Health_Care', 'health_care'), ('Stationery', 'stationery'), ('Rain_Coat', 'rain_coat'), ('Kid’s_Toys', 'kid_toys'), ('Bag', 'bag')], default=('Watch', 'watch'), max_length=20, verbose_name='Product Sub-Category'),
        ),
    ]
