# Generated by Django 3.0.4 on 2020-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200408_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Watch', 'watch'), ('Belt', 'belt'), ('Wallet', 'wallet'), ('Shoe', 'shoe'), ('Sunglass', 'sunglass'), ('Ornaments', 'ornaments'), ('Phrase', 'phrase'), ('Safety Equipment’s ', 'safey equipments'), ('Tools', 'tools'), ('Machinery', 'machinery'), ('Hardware', 'hardware'), ('Sanitary', 'sanitary'), ('Washing_Device', 'washing_device'), ('Water_Purifiers', 'water_purifiers'), ('Kitchen_&_Cleaning', 'kitchen_&_cleaning'), ('CC_Camera', 'cc_camera'), ('Earphone', 'earphone'), ('Scale', 'scale'), ('Storage Device', 'storage_device'), ('Network Device', 'network_device'), ('Health Care', 'health care'), ('Stationery', 'stationery'), ('Rain Coat', 'rain coat'), ('Kid’s Toys', 'kid toys'), ('Bag', 'bag')], default=('Watch', 'watch'), max_length=20, verbose_name='Product Sub-Category'),
        ),
    ]
