# Generated by Django 3.0.4 on 2020-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200408_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MEN', 'men'), ('WOMEN', 'women'), ('CONSTRUCTION', 'construction'), ('HOME DECORATION', 'home decorations'), ('ELECTRONICS', 'electronics'), ('OTHERS', 'others'), ('KIDS WORLD', 'kids world')], default=('MEN', 'men'), max_length=20, verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('WATCH', 'watch'), ('BELT', 'belt'), ('WALLET', 'wallet'), ('WHOE', 'shoe'), ('SUNGLASS', 'sunglass'), ('ORNAMENTS', 'ornaments'), ('PHRASE', 'phrase'), ('SAFETY EQUIPMENTS', 'safey equipments'), ('TOOLS', 'tools'), ('MACHINERY', 'machinery'), ('HARDWARE', 'hardware'), ('SANITARY', 'sanitary'), ('WASHING DEVICE', 'washing device'), ('WATER PURIFIERS', 'water purifiers'), ('KITCHEN & CLEANING', 'kitchen & cleaning'), ('CC CAMERA', 'cc camera'), ('EARPHONE', 'earphone'), ('SCALE', 'scale'), ('STORAGE DEVICE', 'storage device'), ('NETWORK DEVICE', 'network device'), ('HEALTH CARE', 'health care'), ('STATIONERY', 'stationery'), ('RAIN COAT', 'rain coat'), ('KIDS TOYS', 'kid toys'), ('BAG', 'bag')], default=('WATCH', 'watch'), max_length=20, verbose_name='Product Sub-Category'),
        ),
    ]
