# Generated by Django 3.0.4 on 2020-04-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200408_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatenews',
            name='position',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
