# Generated by Django 3.0.4 on 2020-04-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_updatenews_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='trend_images')),
                ('position', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='trend',
        ),
        migrations.AddField(
            model_name='product',
            name='trend_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
