# Generated by Django 3.0.4 on 2020-04-09 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200409_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrendImage',
            new_name='Trend',
        ),
    ]
