# Generated by Django 3.0.4 on 2020-04-09 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200409_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trend',
            options={'verbose_name': 'Trend', 'verbose_name_plural': 'Trends'},
        ),
        migrations.AlterModelOptions(
            name='updatenews',
            options={'verbose_name': 'Updated News', 'verbose_name_plural': 'Updated News'},
        ),
    ]
