# Generated by Django 3.0.4 on 2020-04-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200409_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(max_length=250)),
                ('twitter', models.URLField(max_length=250)),
                ('youtube', models.URLField(max_length=250)),
                ('instagram', models.URLField(max_length=250)),
                ('contact_mail', models.EmailField(max_length=120)),
                ('information_mail', models.URLField(max_length=250)),
                ('customer_care', models.URLField(max_length=250)),
                ('complain_suggesion', models.URLField(max_length=250)),
                ('order_confirmation', models.URLField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Constructions', 'Constructions'), ('Home Decorations', 'Home Decorations'), ('Electronics', 'Electronics'), ('Others', 'Others'), ('Kids World', 'Kids World')], default=('Men', 'Men'), max_length=20, verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('Watch', 'Watch'), ('Belt', 'Belt'), ('Wallet', 'Wallet'), ('Shoe', 'Shoe'), ('Sunglass', 'Sunglass'), ('Ornaments', 'Ornaments'), ('Phrase', 'Phrase'), ('Safety Equipments', 'Safety Equipments'), ('Tools', 'Tools'), ('Machinery', 'Machinery'), ('Hardware', 'Hardware'), ('Sanitary', 'Sanitary'), ('Washing Device', 'Washing Device'), ('Water Purifiers', 'Water Purifiers'), ('Kitchen & Cleaning', 'Kitchen & Cleaning'), ('CC Camera', 'CC Camera'), ('Earphone', 'Earphone'), ('Scale', 'Scale'), ('Storage Device', 'Storage Device'), ('Network Device', 'Network Device'), ('Health Caret', 'Health Care'), ('Stationery', 'Stationery'), ('Rain Coat', 'Rain Coat'), ('Kids Toys', 'Kids Toys'), ('Bag', 'Bag')], default=('Watch', 'Watch'), max_length=20, verbose_name='Product Sub-Category'),
        ),
    ]
