# Generated by Django 3.0.4 on 2020-04-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20200415_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
