# Generated by Django 3.0.4 on 2020-04-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20200419_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentphonenumber',
            name='phone_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Phone Number.', null=True),
        ),
    ]
