# Generated by Django 3.0.4 on 2020-04-19 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0020_auto_20200419_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delevery_charge',
        ),
        migrations.RemoveField(
            model_name='product',
            name='free_delivery',
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField(max_length=11)),
                ('delivery_location', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('city', models.CharField(max_length=20)),
                ('delivery_charge', models.CharField(max_length=50)),
                ('payment_gateway', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
