# Generated by Django 3.0.4 on 2020-04-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20200420_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_gateway',
            field=models.CharField(default='Cash on delivery', max_length=20),
        ),
    ]
