# Generated by Django 3.0.4 on 2020-04-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20200420_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='address',
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_gateway',
            field=models.CharField(default='Cash on delivery.', max_length=20),
        ),
    ]
