# Generated by Django 3.0.4 on 2020-04-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20200420_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='payment_number',
            field=models.CharField(default=35265, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderpayment',
            name='invoice_no',
            field=models.PositiveIntegerField(auto_created=True, unique=True),
        ),
    ]
