# Generated by Django 3.0.4 on 2020-04-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20200420_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='delivery_charge',
            field=models.CharField(default='Depends on courier.', max_length=50),
        ),
    ]
