# Generated by Django 3.0.4 on 2020-04-20 07:11

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20200420_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='invoice_no',
            field=models.PositiveIntegerField(default=apps.product.models.OrderPayment.number, unique=True),
        ),
    ]
