# Generated by Django 3.0.4 on 2020-04-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20200420_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_gateway',
            field=models.CharField(default='Cash on delivery.', editable=False, max_length=50),
        ),
    ]
