# Generated by Django 3.0.4 on 2020-04-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20200420_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
