# Generated by Django 3.0.4 on 2020-04-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20200423_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productphoto',
            name='image',
            field=models.ImageField(help_text='Can add only 3 images please.', upload_to='product_images'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reward Title'),
        ),
    ]
