# Generated by Django 3.0.4 on 2020-04-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200408_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
